### ISSUE TITLE
[macOS] User doesn't have permission to the app path

### ISSUE THREAD

**Issue by vimark1** [Ross-Technologies/SherwoodArch#14]
hey how can I run this?
`make` does not run on macos, I get:
> xcrun: error: invalid active developer path

I am interested in learning about low level programming and virtual machines. 

I would be interested in setting up and eventually contributing to the project if that's something you'd welcome.  Thanks

**Comment by vimark1** [comment]
`make` is running now actually.  I had this problem: https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path

**Comment by vimark1** [comment]
![image](https://user-images.githubusercontent.com/44329742/48405916-18af7f80-e798-11e8-87d6-514b0e8ecc51.png)

I can't get past this page.  What am I doing wrong?  Clicking `Done` does nothing.

**Comment by RossComputerGuy** [comment]
Change the directory path

**Comment by vimark1** [comment]
I’ll try this a bit later. What should I change it to?

**Comment by RossComputerGuy** [comment]
Whatever directory you want it to be, preferably in /User/[name]/
